image: node:14.13.1

before_script:
    - yarn

stages:
    - build
    - test

build-frontend:
    stage: build
    script:
        - yarn workspace frontend build

    cache:
        key: frontend
        paths:
            - packages/frontend/node_modules/

test-frontend:
    stage: test
    script:
        - yarn workspace frontend test

    cache:
        key: frontend
        paths:
            - packages/frontend/node_modules/
